name: Build and run all tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
        os: [ubuntu-latest]
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Cache go modules
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
        restore-keys: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
    - name: Check out code
      uses: actions/checkout@v2
    - name: Get and verify dependencies
      run: go mod download && go mod verify && go get -t ./...
    - name: Go vet
      run: go vet ./...
    - name: Run tests
      run: go test -tags integration -v ./...
      env:
        FOO: bar